CREATE TABLE `CharacterBattleJob` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `character_id` bigint(20) unsigned NOT NULL,
    `dark_knight` bigint(20) unsigned NOT NULL,
    `gunbreaker` bigint(20) unsigned NOT NULL,
    `paladin` bigint(20) unsigned NOT NULL,
    `warrior` bigint(20) unsigned NOT NULL,
    `astrologian` bigint(20) unsigned NOT NULL,
    `scholar` bigint(20) unsigned NOT NULL,
    `white_mage` bigint(20) unsigned NOT NULL,
    `bard` bigint(20) unsigned NOT NULL,
    `black_mage` bigint(20) unsigned NOT NULL,
    `dancer` bigint(20) unsigned NOT NULL,
    `dragoon` bigint(20) unsigned NOT NULL,
    `machinist` bigint(20) unsigned NOT NULL,
    `monk` bigint(20) unsigned NOT NULL,
    `ninja` bigint(20) unsigned NOT NULL,
    `red_mage` bigint(20) unsigned NOT NULL,
    `samurai` bigint(20) unsigned NOT NULL,
    `summoner` bigint(20) unsigned NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code` (`character_id`),
    CONSTRAINT `CharacterBattleJobs_ibfk_1` FOREIGN KEY (`character_id`) REFERENCES `FFCharacter` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;